<?php

/**
 * Baseestados
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $titulo
 * @property integer $pais_id
 * @property boolean $activo
 * @property boolean $by_admin
 * @property integer $created_by
 * @property integer $updated_by
 * @property paises $paises
 * @property Doctrine_Collection $sfGuardUserBululu
 * @property Doctrine_Collection $comunidades
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method varchar             getTitulo()            Returns the current record's "titulo" value
 * @method integer             getPaisId()            Returns the current record's "pais_id" value
 * @method boolean             getActivo()            Returns the current record's "activo" value
 * @method boolean             getByAdmin()           Returns the current record's "by_admin" value
 * @method integer             getCreatedBy()         Returns the current record's "created_by" value
 * @method integer             getUpdatedBy()         Returns the current record's "updated_by" value
 * @method paises              getPaises()            Returns the current record's "paises" value
 * @method Doctrine_Collection getSfGuardUserBululu() Returns the current record's "sfGuardUserBululu" collection
 * @method Doctrine_Collection getComunidades()       Returns the current record's "comunidades" collection
 * @method estados             setId()                Sets the current record's "id" value
 * @method estados             setTitulo()            Sets the current record's "titulo" value
 * @method estados             setPaisId()            Sets the current record's "pais_id" value
 * @method estados             setActivo()            Sets the current record's "activo" value
 * @method estados             setByAdmin()           Sets the current record's "by_admin" value
 * @method estados             setCreatedBy()         Sets the current record's "created_by" value
 * @method estados             setUpdatedBy()         Sets the current record's "updated_by" value
 * @method estados             setPaises()            Sets the current record's "paises" value
 * @method estados             setSfGuardUserBululu() Sets the current record's "sfGuardUserBululu" collection
 * @method estados             setComunidades()       Sets the current record's "comunidades" collection
 * 
 * @package    venexter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseestados extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estados');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('titulo', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('pais_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('by_admin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('created_by', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('updated_by', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('paises', array(
             'local' => 'pais_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('sfGuardUserBululu', array(
             'local' => 'id',
             'foreign' => 'estado_id'));

        $this->hasMany('comunidades', array(
             'local' => 'id',
             'foreign' => 'estado_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'titulo',
             ),
             'unique' => true,
             ));
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             'updated' => 
             array(
              'name' => 'updated_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             ));
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}