<?php

/**
 * BaseperfilesContactos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $perfil_id
 * @property integer $tipo_contacto_id
 * @property varchar $valor
 * @property sfGuardUserBululu $sfGuardUserBululu
 * @property tiposContactos $tiposContactos
 * 
 * @method integer           getPerfilId()          Returns the current record's "perfil_id" value
 * @method integer           getTipoContactoId()    Returns the current record's "tipo_contacto_id" value
 * @method varchar           getValor()             Returns the current record's "valor" value
 * @method sfGuardUserBululu getSfGuardUserBululu() Returns the current record's "sfGuardUserBululu" value
 * @method tiposContactos    getTiposContactos()    Returns the current record's "tiposContactos" value
 * @method perfilesContactos setPerfilId()          Sets the current record's "perfil_id" value
 * @method perfilesContactos setTipoContactoId()    Sets the current record's "tipo_contacto_id" value
 * @method perfilesContactos setValor()             Sets the current record's "valor" value
 * @method perfilesContactos setSfGuardUserBululu() Sets the current record's "sfGuardUserBululu" value
 * @method perfilesContactos setTiposContactos()    Sets the current record's "tiposContactos" value
 * 
 * @package    venexter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseperfilesContactos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('perfiles_contactos');
        $this->hasColumn('perfil_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tipo_contacto_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('valor', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUserBululu', array(
             'local' => 'perfil_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('tiposContactos', array(
             'local' => 'tipo_contacto_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}