<?php

/**
 * Basecomunidades
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $unique_id
 * @property integer $feedback_id
 * @property integer $perfil_id
 * @property integer $pais_id
 * @property integer $estado_id
 * @property varchar $avatar
 * @property varchar $titulo
 * @property clob $descripcion
 * @property sfGuardUserBululu $sfGuardUserBululu
 * @property comunidades $comunidades
 * @property paises $paises
 * @property estados $estados
 * 
 * @method integer           getId()                Returns the current record's "id" value
 * @method varchar           getUniqueId()          Returns the current record's "unique_id" value
 * @method integer           getFeedbackId()        Returns the current record's "feedback_id" value
 * @method integer           getPerfilId()          Returns the current record's "perfil_id" value
 * @method integer           getPaisId()            Returns the current record's "pais_id" value
 * @method integer           getEstadoId()          Returns the current record's "estado_id" value
 * @method varchar           getAvatar()            Returns the current record's "avatar" value
 * @method varchar           getTitulo()            Returns the current record's "titulo" value
 * @method clob              getDescripcion()       Returns the current record's "descripcion" value
 * @method sfGuardUserBululu getSfGuardUserBululu() Returns the current record's "sfGuardUserBululu" value
 * @method comunidades       getComunidades()       Returns the current record's "comunidades" value
 * @method paises            getPaises()            Returns the current record's "paises" value
 * @method estados           getEstados()           Returns the current record's "estados" value
 * @method comunidades       setId()                Sets the current record's "id" value
 * @method comunidades       setUniqueId()          Sets the current record's "unique_id" value
 * @method comunidades       setFeedbackId()        Sets the current record's "feedback_id" value
 * @method comunidades       setPerfilId()          Sets the current record's "perfil_id" value
 * @method comunidades       setPaisId()            Sets the current record's "pais_id" value
 * @method comunidades       setEstadoId()          Sets the current record's "estado_id" value
 * @method comunidades       setAvatar()            Sets the current record's "avatar" value
 * @method comunidades       setTitulo()            Sets the current record's "titulo" value
 * @method comunidades       setDescripcion()       Sets the current record's "descripcion" value
 * @method comunidades       setSfGuardUserBululu() Sets the current record's "sfGuardUserBululu" value
 * @method comunidades       setComunidades()       Sets the current record's "comunidades" value
 * @method comunidades       setPaises()            Sets the current record's "paises" value
 * @method comunidades       setEstados()           Sets the current record's "estados" value
 * 
 * @package    venexter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecomunidades extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comunidades');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('unique_id', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('feedback_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('perfil_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pais_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('estado_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('avatar', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('titulo', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUserBululu', array(
             'local' => 'perfil_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('comunidades', array(
             'local' => 'feedback_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('paises', array(
             'local' => 'pais_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('estados', array(
             'local' => 'estado_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             'updated' => 
             array(
              'name' => 'updated_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             ));
        $this->actAs($timestampable0);
    }
}