<?php

/**
 * BaseperfilesFeed
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $unique_id
 * @property integer $feedback_id
 * @property integer $perfil_id
 * @property clob $descripcion
 * @property sfGuardUserBululu $sfGuardUserBululu
 * @property perfilesFeed $perfilesFeed
 * 
 * @method integer           getId()                Returns the current record's "id" value
 * @method varchar           getUniqueId()          Returns the current record's "unique_id" value
 * @method integer           getFeedbackId()        Returns the current record's "feedback_id" value
 * @method integer           getPerfilId()          Returns the current record's "perfil_id" value
 * @method clob              getDescripcion()       Returns the current record's "descripcion" value
 * @method sfGuardUserBululu getSfGuardUserBululu() Returns the current record's "sfGuardUserBululu" value
 * @method perfilesFeed      getPerfilesFeed()      Returns the current record's "perfilesFeed" value
 * @method perfilesFeed      setId()                Sets the current record's "id" value
 * @method perfilesFeed      setUniqueId()          Sets the current record's "unique_id" value
 * @method perfilesFeed      setFeedbackId()        Sets the current record's "feedback_id" value
 * @method perfilesFeed      setPerfilId()          Sets the current record's "perfil_id" value
 * @method perfilesFeed      setDescripcion()       Sets the current record's "descripcion" value
 * @method perfilesFeed      setSfGuardUserBululu() Sets the current record's "sfGuardUserBululu" value
 * @method perfilesFeed      setPerfilesFeed()      Sets the current record's "perfilesFeed" value
 * 
 * @package    venexter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseperfilesFeed extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('perfiles_feed');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('unique_id', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('feedback_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('perfil_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('descripcion', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUserBululu', array(
             'local' => 'perfil_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('perfilesFeed', array(
             'local' => 'feedback_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'titulo',
             ),
             'unique' => true,
             ));
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             'updated' => 
             array(
              'name' => 'updated_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             ));
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}