<?php

/**
 * BasesfGuardUserBululu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $unique_id
 * @property integer $user_id
 * @property varchar $foto_avatar
 * @property date $fecha_nacimiento
 * @property integer $sexo_id
 * @property varchar $profesion
 * @property varchar $video_url
 * @property integer $pais_id
 * @property integer $estado_id
 * @property sfGuardUser $sfGuardUser
 * @property sexos $sexos
 * @property paises $paises
 * @property estados $estados
 * @property Doctrine_Collection $perfilesContactos
 * @property Doctrine_Collection $comunidades
 * @property Doctrine_Collection $perfilesFeed
 * @property Doctrine_Collection $perfilesFollow
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method varchar             getUniqueId()          Returns the current record's "unique_id" value
 * @method integer             getUserId()            Returns the current record's "user_id" value
 * @method varchar             getFotoAvatar()        Returns the current record's "foto_avatar" value
 * @method date                getFechaNacimiento()   Returns the current record's "fecha_nacimiento" value
 * @method integer             getSexoId()            Returns the current record's "sexo_id" value
 * @method varchar             getProfesion()         Returns the current record's "profesion" value
 * @method varchar             getVideoUrl()          Returns the current record's "video_url" value
 * @method integer             getPaisId()            Returns the current record's "pais_id" value
 * @method integer             getEstadoId()          Returns the current record's "estado_id" value
 * @method sfGuardUser         getSfGuardUser()       Returns the current record's "sfGuardUser" value
 * @method sexos               getSexos()             Returns the current record's "sexos" value
 * @method paises              getPaises()            Returns the current record's "paises" value
 * @method estados             getEstados()           Returns the current record's "estados" value
 * @method Doctrine_Collection getPerfilesContactos() Returns the current record's "perfilesContactos" collection
 * @method Doctrine_Collection getComunidades()       Returns the current record's "comunidades" collection
 * @method Doctrine_Collection getPerfilesFeed()      Returns the current record's "perfilesFeed" collection
 * @method Doctrine_Collection getPerfilesFollow()    Returns the current record's "perfilesFollow" collection
 * @method sfGuardUserBululu   setId()                Sets the current record's "id" value
 * @method sfGuardUserBululu   setUniqueId()          Sets the current record's "unique_id" value
 * @method sfGuardUserBululu   setUserId()            Sets the current record's "user_id" value
 * @method sfGuardUserBululu   setFotoAvatar()        Sets the current record's "foto_avatar" value
 * @method sfGuardUserBululu   setFechaNacimiento()   Sets the current record's "fecha_nacimiento" value
 * @method sfGuardUserBululu   setSexoId()            Sets the current record's "sexo_id" value
 * @method sfGuardUserBululu   setProfesion()         Sets the current record's "profesion" value
 * @method sfGuardUserBululu   setVideoUrl()          Sets the current record's "video_url" value
 * @method sfGuardUserBululu   setPaisId()            Sets the current record's "pais_id" value
 * @method sfGuardUserBululu   setEstadoId()          Sets the current record's "estado_id" value
 * @method sfGuardUserBululu   setSfGuardUser()       Sets the current record's "sfGuardUser" value
 * @method sfGuardUserBululu   setSexos()             Sets the current record's "sexos" value
 * @method sfGuardUserBululu   setPaises()            Sets the current record's "paises" value
 * @method sfGuardUserBululu   setEstados()           Sets the current record's "estados" value
 * @method sfGuardUserBululu   setPerfilesContactos() Sets the current record's "perfilesContactos" collection
 * @method sfGuardUserBululu   setComunidades()       Sets the current record's "comunidades" collection
 * @method sfGuardUserBululu   setPerfilesFeed()      Sets the current record's "perfilesFeed" collection
 * @method sfGuardUserBululu   setPerfilesFollow()    Sets the current record's "perfilesFollow" collection
 * 
 * @package    venexter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserBululu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_bululu');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('unique_id', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('foto_avatar', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('fecha_nacimiento', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('sexo_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'genero / Masculino - Femenino - Otro',
             ));
        $this->hasColumn('profesion', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('video_url', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('pais_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('estado_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('sexos', array(
             'local' => 'sexo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('paises', array(
             'local' => 'pais_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('estados', array(
             'local' => 'estado_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('perfilesContactos', array(
             'local' => 'id',
             'foreign' => 'perfil_id'));

        $this->hasMany('comunidades', array(
             'local' => 'id',
             'foreign' => 'perfil_id'));

        $this->hasMany('perfilesFeed', array(
             'local' => 'id',
             'foreign' => 'perfil_id'));

        $this->hasMany('perfilesFollow', array(
             'local' => 'id',
             'foreign' => 'follow_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             'updated' => 
             array(
              'name' => 'updated_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             ));
        $this->actAs($timestampable0);
    }
}