<?php

/**
 * Basesexos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $sfGuardUserBululu
 * 
 * @method Doctrine_Collection getSfGuardUserBululu() Returns the current record's "sfGuardUserBululu" collection
 * @method sexos               setSfGuardUserBululu() Sets the current record's "sfGuardUserBululu" collection
 * 
 * @package    venexter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesexos extends constantes
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUserBululu', array(
             'local' => 'id',
             'foreign' => 'sexo_id'));
    }
}