<?php

/**
 * Baseconstantes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $titulo
 * @property clob $descripcion
 * @property varchar $imagen
 * @property boolean $activo
 * @property string $tipo
 * 
 * @method integer    getId()          Returns the current record's "id" value
 * @method varchar    getTitulo()      Returns the current record's "titulo" value
 * @method clob       getDescripcion() Returns the current record's "descripcion" value
 * @method varchar    getImagen()      Returns the current record's "imagen" value
 * @method boolean    getActivo()      Returns the current record's "activo" value
 * @method string     getTipo()        Returns the current record's "tipo" value
 * @method constantes setId()          Sets the current record's "id" value
 * @method constantes setTitulo()      Sets the current record's "titulo" value
 * @method constantes setDescripcion() Sets the current record's "descripcion" value
 * @method constantes setImagen()      Sets the current record's "imagen" value
 * @method constantes setActivo()      Sets the current record's "activo" value
 * @method constantes setTipo()        Sets the current record's "tipo" value
 * 
 * @package    venexter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseconstantes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('constantes');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('titulo', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('imagen', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('tipo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');

        $this->setSubClasses(array(
             'sexos' => 
             array(
              'tipo' => 'SEX',
             ),
             'catComunidades' => 
             array(
              'tipo' => 'CATCOM',
             ),
             'tiposContactos' => 
             array(
              'tipo' => 'TIPCON',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'titulo',
              1 => 'tipo',
             ),
             'unique' => true,
             ));
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             'updated' => 
             array(
              'name' => 'updated_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             ));
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}