<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/11/03 16:09:03
sfConfig::add(array(
  'app_sf_guard_plugin_allow_login_with_email' => true,
  'app_sf_guard_plugin_default_from_email' => array (
  'webmaster@sibeliusfest.com' => 'Sibelius Fest',
),
  'app_sf_guard_plugin_default_subject' => 'Recuperacion de clave para',
  'app_sf_guard_plugin_default_confirm_change' => 'Nueva Contraseña para',
));
