<?php

/**
 * catComunidadesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class catComunidadesTable extends constantesTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object catComunidadesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('catComunidades');
    }
}