<?php

/**
 * comunidadesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class comunidadesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object comunidadesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('comunidades');
    }
}