<?php

/**
 * estadosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class estadosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object estadosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('estados');
    }
}