<?php

/**
 * paisesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class paisesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object paisesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('paises');
    }
}