<?php

/**
 * perfilesFollowTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class perfilesFollowTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object perfilesFollowTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('perfilesFollow');
    }
}