<?php

/**
 * perfilesContactosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class perfilesContactosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object perfilesContactosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('perfilesContactos');
    }
}