<?php

/**
 * perfilesFeedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class perfilesFeedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object perfilesFeedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('perfilesFeed');
    }
}