<?php

/**
 * sfGuardUserBululuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserBululuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserBululuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserBululu');
    }
}