<?php

/**
 * tiposContactosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tiposContactosTable extends constantesTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object tiposContactosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tiposContactos');
    }
}