# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_DEPRECATED)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:

    login_module:         sfGuardAuth
    login_action:         signin

    secure_module:        sfGuardAuth
    secure_action:        secure

    enabled_modules:
      - default
      - sfGuardAuth
      - sfGuardUser
      - sfGuardForgotPassword

    # Form security secret (CSRF protection)
    csrf_secret:            5c152e4a3b82fe86b0bbd7e23446c77b9e316afe

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    #standard_helpers:       [Partial, Cache, I18N, Date]
    i18n:                   true    
    #default_culture:        es_VE
    default_culture:        es
    charset:                utf-8