<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/11/03 16:02:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=venexter',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
