<?php
// auto-generated by sfViewConfigHandler
// date: 2013/11/03 17:23:00
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('../bootstrap/css/bootstrap.min.css', '', array ());
  $response->addStylesheet('../bootstrap/css/bootstrap-responsive.min.css', '', array ());
  $response->addStylesheet('common.css', '', array ());
  $response->addStylesheet('bootstrap-fix.css', '', array ());
  $response->addJavascript('http://code.jquery.com/jquery.js', '', array ());
  $response->addJavascript('../bootstrap/js/bootstrap.min.js', '', array ());


